services:
  # --- CONTENEDOR DE BASE DE DATOS ---
  database_container:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: database_host
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SqlPassword2025!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - cinema-vnet

  # --- CONTENEDOR DE TU APP MVC ---
  web_container:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cinema_master
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DefaultConnection=Server=database_host,1433;Database=CinemaMasterTicketsMVC;User Id=sa;Password=SqlPassword2025!;TrustServerCertificate=True
      - AdminSettings__Email=admin@site.com
      - AdminSettings__Password=Admin123!
      - MovieApi__ApiKey= #Pega aqui tu clave personal para usar la API de TMDB
    ports:
      - "8080:80"
    depends_on:
      - database_container
    networks:
      - cinema-vnet

networks:
  cinema-vnet:
    driver: bridge

volumes:
  sql_data: