// <auto-generated />
using System;
using CinemaMasterTicketsMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaMasterTicketsMVC.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251220111618_m2")]
    partial class m2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.AddOn", b =>
                {
                    b.Property<int>("AddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddOnId"));

                    b.Property<string>("AddonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AddOnId");

                    b.ToTable("AddOns");

                    b.HasData(
                        new
                        {
                            AddOnId = 1,
                            AddonName = "Palomitas Grandes",
                            Price = 5.00m
                        },
                        new
                        {
                            AddOnId = 2,
                            AddonName = "Bebida Grande",
                            Price = 3.50m
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.BoxOffice", b =>
                {
                    b.Property<int>("BoxOfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoxOfficeId"));

                    b.Property<string>("BoxOfficeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoxOfficeId");

                    b.ToTable("BoxOffices");

                    b.HasData(
                        new
                        {
                            BoxOfficeId = 1,
                            BoxOfficeName = "Taquilla Principal"
                        },
                        new
                        {
                            BoxOfficeId = 2,
                            BoxOfficeName = "Taquilla Rápida"
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FidelityPoints")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Calle Falsa 123",
                            City = "Madrid",
                            CreatedDate = new DateTime(2025, 11, 20, 12, 16, 17, 429, DateTimeKind.Local).AddTicks(3869),
                            Email = "ana@email.com",
                            FidelityPoints = 150,
                            FirstName = "Ana",
                            LastName = "Martínez",
                            isActive = true
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "Avenida Siempreviva 42",
                            City = "Barcelona",
                            CreatedDate = new DateTime(2025, 12, 5, 12, 16, 17, 429, DateTimeKind.Local).AddTicks(3875),
                            Email = "javier@email.com",
                            FidelityPoints = 50,
                            FirstName = "Javier",
                            LastName = "López",
                            isActive = true
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BoxOfficeId")
                        .HasColumnType("int");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BoxOfficeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BoxOfficeId = 1,
                            DNI = "12345678-A",
                            Email = "laura@cinema.com",
                            Firstname = "Laura",
                            Lastname = "Gómez"
                        },
                        new
                        {
                            EmployeeId = 2,
                            BoxOfficeId = 1,
                            DNI = "87654321-B",
                            Email = "pedro@cinema.com",
                            Firstname = "Pedro",
                            Lastname = "Ruiz"
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieAPIId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverView")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            AddedAt = new DateTime(2025, 12, 13, 12, 16, 17, 429, DateTimeKind.Local).AddTicks(4079),
                            DurationMinutes = 150,
                            Genre = "Sci-Fi",
                            MovieAPIId = "101",
                            OverView = "Viaje épico a través de la galaxia.",
                            PosterUrl = "/img/cosmic.jpg",
                            Title = "Aventura Cósmica"
                        },
                        new
                        {
                            MovieId = 2,
                            AddedAt = new DateTime(2025, 12, 15, 12, 16, 17, 429, DateTimeKind.Local).AddTicks(4085),
                            DurationMinutes = 90,
                            Genre = "Thriller",
                            MovieAPIId = "102",
                            OverView = "Un detective debe resolver un crimen en una vieja mansión.",
                            PosterUrl = "/img/mansion.jpg",
                            Title = "Misterio en la Mansión"
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Capacity = 100
                        },
                        new
                        {
                            RoomId = 2,
                            Capacity = 50
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("SeatId");

                    b.HasIndex("RoomId");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            SeatId = 1,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 2,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 3,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 4,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 5,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 6,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 7,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 8,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 9,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 10,
                            RoomId = 1
                        },
                        new
                        {
                            SeatId = 11,
                            RoomId = 2
                        },
                        new
                        {
                            SeatId = 12,
                            RoomId = 2
                        },
                        new
                        {
                            SeatId = 13,
                            RoomId = 2
                        },
                        new
                        {
                            SeatId = 14,
                            RoomId = 2
                        },
                        new
                        {
                            SeatId = 15,
                            RoomId = 2
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.HasIndex("MovieId");

                    b.HasIndex("RoomId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            MovieId = 1,
                            Price = 8.50m,
                            RoomId = 1,
                            StartTime = new DateTime(2025, 12, 20, 14, 16, 17, 429, DateTimeKind.Local).AddTicks(4105),
                            Status = "Active"
                        },
                        new
                        {
                            SessionId = 2,
                            MovieId = 2,
                            Price = 7.00m,
                            RoomId = 2,
                            StartTime = new DateTime(2025, 12, 20, 17, 16, 17, 429, DateTimeKind.Local).AddTicks(4112),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.SessionSeat", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "SeatId");

                    b.HasIndex("SeatId");

                    b.ToTable("SessionSeats");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            SeatId = 1
                        },
                        new
                        {
                            SessionId = 1,
                            SeatId = 2
                        },
                        new
                        {
                            SessionId = 1,
                            SeatId = 3
                        },
                        new
                        {
                            SessionId = 1,
                            SeatId = 4
                        },
                        new
                        {
                            SessionId = 1,
                            SeatId = 5
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("EmailToSend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PurchasedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<bool>("SoldAtBoxOffice")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TicketId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SessionId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            CustomerId = 1,
                            EmailToSend = "ana@email.com",
                            PaymentMethod = "Credit Card",
                            PurchasedAt = new DateTime(2025, 12, 20, 12, 11, 17, 429, DateTimeKind.Local).AddTicks(4193),
                            SessionId = 1,
                            SoldAtBoxOffice = false,
                            TotalPrice = 13.50m
                        },
                        new
                        {
                            TicketId = 2,
                            EmailToSend = "guest@email.com",
                            EmployeeId = 1,
                            PaymentMethod = "Cash",
                            PurchasedAt = new DateTime(2025, 12, 20, 12, 14, 17, 429, DateTimeKind.Local).AddTicks(4199),
                            SessionId = 1,
                            SoldAtBoxOffice = true,
                            TotalPrice = 8.50m
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.TicketAddOn", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("AddOnId")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "AddOnId");

                    b.HasIndex("AddOnId");

                    b.ToTable("TicketAddOns");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            AddOnId = 1
                        },
                        new
                        {
                            TicketId = 1,
                            AddOnId = 2
                        });
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.TicketSeat", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("TicketId", "SeatId", "SessionId");

                    b.HasIndex("SeatId");

                    b.HasIndex("SessionId");

                    b.ToTable("TicketSeats");

                    b.HasData(
                        new
                        {
                            TicketId = 1,
                            SeatId = 6,
                            SessionId = 1
                        },
                        new
                        {
                            TicketId = 1,
                            SeatId = 7,
                            SessionId = 1
                        },
                        new
                        {
                            TicketId = 2,
                            SeatId = 8,
                            SessionId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Employee", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.BoxOffice", "BoxOffice")
                        .WithMany("Employees")
                        .HasForeignKey("BoxOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoxOffice");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Seat", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.Room", "Room")
                        .WithMany("Seats")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Session", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.Movie", "Movie")
                        .WithMany("Sessions")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaMasterTicketsMVC.Models.Room", "Room")
                        .WithMany("Sessions")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.SessionSeat", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.Seat", "Seat")
                        .WithMany("SessionSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaMasterTicketsMVC.Models.Session", "Session")
                        .WithMany("SessionSeats")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Ticket", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CinemaMasterTicketsMVC.Models.Employee", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CinemaMasterTicketsMVC.Models.Session", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.TicketAddOn", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.AddOn", "AddOn")
                        .WithMany("TicketAddOns")
                        .HasForeignKey("AddOnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaMasterTicketsMVC.Models.Ticket", "Ticket")
                        .WithMany("TicketAddOns")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddOn");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.TicketSeat", b =>
                {
                    b.HasOne("CinemaMasterTicketsMVC.Models.Seat", "Seat")
                        .WithMany("TicketSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaMasterTicketsMVC.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CinemaMasterTicketsMVC.Models.Ticket", "Ticket")
                        .WithMany("TicketSeats")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("Session");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.AddOn", b =>
                {
                    b.Navigation("TicketAddOns");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.BoxOffice", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Employee", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Movie", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Room", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Seat", b =>
                {
                    b.Navigation("SessionSeats");

                    b.Navigation("TicketSeats");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Session", b =>
                {
                    b.Navigation("SessionSeats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("CinemaMasterTicketsMVC.Models.Ticket", b =>
                {
                    b.Navigation("TicketAddOns");

                    b.Navigation("TicketSeats");
                });
#pragma warning restore 612, 618
        }
    }
}
