services: #Esta es la seccion donde definimos los contenedores que tendra nuestra aplicacion
  # Contenedor de la base de datos
  database_container: # este es el nombre logico del servicio
    image: mcr.microsoft.com/mssql/server:2022-latest # Esta es la imagen docker que usaremos
    container_name: database_host # Nombre del contenedor cuando se ejecuta
    environment: #Variaables de entorno para configurar SqlServer
      - ACCEPT_EULA=Y #Esto es obligatorio aceptamos los terminos de licencia de Microsoft, si no el contenedor no arranca
      - MSSQL_SA_PASSWORD=SqlPassword2025! #contraseña del usuario SA o el administrador de SQL server
      - MSSQL_PID=Developer #En esta linea se define el tipo de licencia, en este caso es developer
    ports: #Puertos que usara el contenedor
      - "1433:1433" #Aqui el 1433 del pc se conectara al 1433 del contenedor 
    volumes: #Define volumenes persistentes o datos que no se pierden
      - sql_data:/var/opt/mssql 
    networks: #networks define a que red Docker pertenece el contenedor
      - cinema-vnet #red virtual

  # Contenedor de la app mvc
  web_container:
    build: #con esto indicamos que no vamos a usar una imagen prehecha si no que se va a construir
      context: ./ #ruta que marca el directorio actual del proyecto-> es la carpeta desde donde Docker puede acceder a archivos
      dockerfile: ./Dockerfile # El dockerfile es el archivo donde se encuentran las instrucciones para construir la imagen
    container_name: cinema_master # nombre del contenedor de la app cuando se ejecuta
    environment: #variables de entorno que usara la app dentro del contenedor
      - ASPNETCORE_ENVIRONMENT=Development # Esto indica que la app corre en modo desarrollo
      - ASPNETCORE_URLS=http://0.0.0.0:80 # Esto le dice que escuche conexiones desde fuera del contenedor en el puerto 80
       # cadena de conexion, se incluye el nombre del contenedor de la bd, el puerto sql, y las credenciales definidas arriba
      - ConnectionStrings__DefaultConnection=Server=database_host,1433;Database=CinemaMasterTicketsMVC;User Id=sa;Password=SqlPassword2025!;TrustServerCertificate=True 
      - AdminSettings__Email=admin@site.com #email de usuari admin -> modificamos estas variables en azure por seguridad
      - AdminSettings__Password=Admin123! #contraseña de usuario admin
      - MovieApi__ApiKey=e30c1ae43fe34f0a90b23ecb086b8571  #api key para consumir datos de TMDB
    ports:
      - "8080:80" #puertos de la aplicacion web 8080 es el puerto del ordenador y el 80 es el puerto dentro del contenedor
    depends_on:
      - database_container #aqui se define la depedencia entre los dos servicios, el web container se arranca despues de la base de datos
    networks:
      - cinema-vnet #red del contenedor se conecta a la misma red de la base de datos para la comunicacion

networks: #aqui se definen redes docker personalizadas
  cinema-vnet:
    driver: bridge #red privada esto quiere decir que los contenedores se ven entre si por nombre

volumes: #Datos persistentes 
  sql_data: #volumen donde se guardan los datos y persiste aunque se borren los contenedores